{% set version = "0.3.7" %}

package:
  name: multiurl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/multiurl/multiurl-{{ version }}.tar.gz
  sha256: 4201563fc8989baca7b525fdc69d4cd5a6c0cef4f303559710b9890021aab6d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil
    - pytz
    - requests
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - multiurl

about:
  home: https://github.com/ecmwf/multiurl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download several URL as one

extra:
  recipe-maintainers:
    - raybellwaves
