{% set version = "0.2.1" %}

package:
  name: multiurl
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/multiurl/multiurl-{{ version }}.tar.gz
  sha256: 12d2621a227ba559b0fa71473359f1b461ae2cc41d059b74c2cbddfd73bd7162

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - python-dateutil
    - pytz
    - requests
    - tqdm

test:
  imports:
    - multiurl

about:
  home: https://github.com/ecmwf/multiurl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package to download several URL as one

extra:
  recipe-maintainers:
    - raybellwaves
